### ISSUE TITLE
bug: world and provisioning fixtures fail under full-suite parallel load, pass in isolation

### ISSUE THREAD

**Issue by johnitvn** [ecoma-io/release-craft#154]
## Prerequisites

- [x] I searched existing issues for a duplicate
- [x] This is not a security vulnerability

## Area

Toolchain (build · test · lint · format · typecheck)

## What happened?

One `pnpm test` run (the pre-push hook's suite, 2026-09-10 ~11:23 local) failed two test files that pass in isolation and passed on the immediately following identical-tree run:

- `test/dogfood/world.test.ts` — "closes the seeded repository into a world the planner's own door accepts" — failed in 194 ms.
- `test/action/provisioning.test.ts` — "the scripts-free install completes where the lifecycle scripts die" — failed in 2 093 ms.

Suite totals of the failing run: `Test Files 2 failed | 87 passed (89)`, `Tests 2 failed | 1310 passed (1312)`, duration 54.76 s. The assertion text of both failures was not captured (the hook output was read through `tail -30`).

Observations that followed on the same tree (branch `johnitvn/provisioning-policy-materialization`, commit 8081e4d, pin `@ecoma-io/archkeep@0.24.1`):

1. The two files run together in isolation: both passed (1.81 s total).
2. A full `pnpm test` run: no failures (55.6 s wall) — the run Moon then cached under hash `f6025e56`, the same hash the failing run had printed.

So the same input hash produced a failed verdict and a clean verdict in consecutive runs; the suite's verdict is not a function of the tree alone. This matches the contention class already recorded in #132 ("the V7 windows time out under parallel CPU contention (~63 s vs the 45 s cap) and pass in isolation") but names two different files and two fast-fail (non-timeout) modes.

## What did you expect?

A suite member's verdict should be a function of the tree it runs on, not of the machine's momentary parallel load. Both fixtures spawn real processes (`git`, real pnpm installs) and are the plausible contention victims; if their assertions depend on timing or on output interleaving under vitest's parallel scheduler, the dependence should be named and removed (serialize the spawned-process legs, or make the assertion wait on the condition instead of the race).

## Reproduction steps

Not reliably reproducible: one failure observed once under pre-push full-suite load; two subsequent configurations (isolated pair, full live suite) on the identical tree passed. What did run, verbatim:

```
git push          # triggers lefthook pre-push: pnpm test  → 2 failed | 1310 passed
pnpm exec vitest run test/dogfood/world.test.ts test/action/provisioning.test.ts
                  # → 2 passed
pnpm test         # → 0 failed (55.6 s live run)
```

## Environment

```
node --version  → v24.x
pnpm --version  → 11.25.0
pnpm exec moon --version → 2.5.4
OS: Linux (Debian), 8 vCPU (i7-10700K)
```

**Comment by johnitvn** [comment]
Third observation of this class, 2026-09-10 ~11:5x local: the lefthook pre-push `pnpm test` in a separate worktree of this repository (branch `johnitvn/adr-registry-dialect`, docs-only change set — ADR frontmatter, zero product or test files) failed the full suite once; the immediate rerun passed 89/89 files (56.5 s). Failing file names were not captured this time either (output filtered); posting for the pattern's tally: one failure per ~4-5 full-suite runs under parallel load on this 8-vCPU machine.

**Comment by johnitvn** [comment]
Duplicate search (as the template requires): [flake OR timeout OR contention OR world.test OR provisioning.test] over all states returns only #132 (V7 window timeouts under contention — the ~45 s budget class, not these sub-3 s fixture failures), #144 (suite-without-build ordering, different mode), #136 (closed, runtime budget). No duplicate; this issue stands as the fast-fail fixture class.

**Comment by johnitvn** [comment]
Closed by PR #168, merged through the merge queue as fc6fa72 (squash on faf0d9f). Both fixture halves are fixed and the composition root cause is proven — reviewer-verified first-hand on the final head (ReviewerF168):

**The mechanism (both halves, one cause).** git exports GIT_DIR/GIT_WORK_TREE into hook subprocess environments: every failure ever captured here happened under `git push` → lefthook pre-push ambient; runs under moon/vitest without the hook env never reproduced it (two independent full-suite 1312/1312 greens with the fixture strip absent — the datapoint that refuted the earlier agent-marker attribution). With GIT_DIR set: `lefthook install`'s `git rev-parse` finds a repository inside the fixture's non-git materialization (install exits 0 — the provisioning assertion's exact failure text), and the dogfood closure's git reads the ambient checkout's history instead of the seeded world.

**Verification (all first-hand by the independent reviewer on faf0d9f):**
- Provisioning composition kill: hook-equivalent ambient + pre-fix raw install env → gate fails with the exact recorded 'unflagged install exited 0'; current hermetic floor under the same ambient → green (4.4s).
- World mirror kill: closure floor reverted + hook ambient → `expected commits length 2 but got 86` DETERMINISTICALLY (the 84-86 drift signature, now reproducible on demand); floor restored → seeded 2 passes.
- One-variable control: bare install exits 1, identical tree + GIT_DIR exits 0 (lefthook prepare succeeds, config added).
- Floor mutation: letting GIT_DIR through hermeticGitEnv → both gates fail; reverted clean.
- Killable pins landed: INSTALL_ENV carries none of CLAUDECODE/CLAUDE_CODE/AGENT (+ NDJSON discriminator); closure spawnEnv carries none of GIT_DIR/GIT_WORK_TREE/GIT_INDEX_FILE/GIT_CONFIG_COUNT — both mutation-captured.
- Load dimension (recorded under #132): pre-fix 4x parallel = 96-97 failures/run across 13 files; post-fix maxWorkers:4 → 12/12 across 3 consecutive 4x-parallel repetitions plus the reviewer's own 4x repetition (4/4, 1312 tests each); no testTimeout bumps.

Honest record: the agent-marker chain (pnpm NDJSON reporter) is real but reporter-only — refuted as the historical trigger; it survives as hermetic hardening behind the killable INSTALL_ENV pin.
